const config = require("../config.js");
const { version } = require('../package.json');

module.exports = {
// Main variables (don't touch unless you know what you're doing)
version: "3.0.5",
versionCodename: "Starry Gate",
versionString: version,
isforgescriptdev: "off",
release_type: "Stable",
pre_release: "on",
DevReleaseTypeToSet: "Canary",
buildNumber: "2431",
buildStatus: "Pending review",
buildBranch: "canary",
buildDate: "1789274471341",
showbuildinfo: "on",
AllowBotMembers: config.AllowBotMembers,
prefix: config.prefix,
botinvitationmessage: "on",
startupsystem: "off",
startupchannel: "",
errorlogging: "off",
errorchannel: "",
servermemberrequirement: "0",
embedcolor: config.Embedcolor,
originalembedcolor: config.Embedcolor,
// Feature variables
suggestionchannel: "",
pollchannel: "",
msglogdeletechannel: "",
msglogeditchannel: "",
banlogschannel: "",
unbanlogschannel: "",
integrationlogchannel: "",
welcomermessage: "Welcome to the server, <user.username>!",
welcomerchannel: "",
welcomertype: "text",
welcomermessageembedcolor: "#1F8B4C",
welcomersystem: "off",
leavechannel: "",
leavesystem: "off",
leavetype: "text",
leavemessageembedcolor: "#ED4245",
leavemessage: "Goodbye, <user.username>! We now have <server.totalMembers> members left!",
levelingsystem: "off",
level: "1",
previouslevel: "0",
xp: "0",
xpLimit: "10",
levelingmessage: "<user.username> has leveled UP! Their level is now <newlevel>!",
levelupmessagechannel: "",
levelingmessagefeature: "off",
levelingresetonleave: "off",
levelingexcludedchannels: "none",
levelingexcludedcategories: "none",
levelingexcludedroles: "none",
autoreplyping: "off",
anonymous: "off",
includebots: "on",
// Game variables
trivia_type: "multiple",
trivia_difficulty: "medium",
flood_difficulty: 13,
wyr: {option1votes: "0", option2votes: "0"},
hangman_theme: "nature"
}
